CREATE ROLE $DB_USER WITH
  LOGIN
  NOSUPERUSER
  NOCREATEROLE
  NOREPLICATION;

ALTER USER $DB_USER WITH
    ENCRYPTED PASSWORD '$DB_PASSWORD';

CREATE DATABASE $DB_NAME WITH
    OWNER = $DB_USER
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TEMPLATE = template0
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;

\connect $DB_NAME;

\ir tables.sql
