version: '3.8'
name: marketplace

services:
  db:
    image: docker.io/library/postgres:16.2
    container_name: marketplace_db
    restart: always
    networks:
      - marketplace
    ports:
      - '5432:5432'
    environment:
      COMPOSE: true
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

networks:
  marketplace:
    name: marketplace_network

volumes:
  data: