version: '3.8'
name: marketplace

services:

  db:
    image: docker.io/library/postgres:16.2-alpine
    container_name: marketplace-db
    restart: always
    networks:
      - marketplace
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      COMPOSE: true
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

networks:
  marketplace:
    name: marketplace-network

volumes:
  dbdata: