version: "3.8"
name: marketplace

services:

  db:
    image: postgres:16.2-alpine
    container_name: marketplace-db
    restart: always
    networks:
      - marketplace
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DB_ADMIN_USER}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

networks:
  marketplace:
    name: marketplace-network

volumes:
  dbdata: